*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:41:22 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:28:10
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: e24c7034d9af
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5625f713c410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x5625f713c410 pid: 19 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19)
spawned uWSGI worker 1 (pid: 20, cores: 1)
spawned uWSGI worker 2 (pid: 22, cores: 1)
Python auto-reloader enabled
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:80'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework_simplejwt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 124, in response_for_exception
    security_logger.error(
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/usr/local/lib/python3.9/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 403, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 381, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/usr/local/lib/python3.9/site-packages/django/views/debug.py", line 99, in get_caller
    resolver_match = resolve(request.path)
  File "/usr/local/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 638, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 690, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 683, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/mysite6/./mysite6/urls.py", line 19, in <module>
    from app01.views import AdminView, LoginView
  File "/var/www/html/mysite6/./app01/views.py", line 5, in <module>
    from rest_framework.viewsets import ModelViewSet
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 27, in <module>
    from rest_framework import generics, mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/__init__.py", line 33, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_simplejwt.authentication.JWTAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'rest_framework_simplejwt'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework_simplejwt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
    callback = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 704, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 683, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/mysite6/./mysite6/urls.py", line 19, in <module>
    from app01.views import AdminView, LoginView
  File "/var/www/html/mysite6/./app01/views.py", line 5, in <module>
    from rest_framework.viewsets import ModelViewSet
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 27, in <module>
    from rest_framework import generics, mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/__init__.py", line 33, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_simplejwt.authentication.JWTAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'rest_framework_simplejwt'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework_simplejwt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
    callback = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 704, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 683, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/mysite6/./mysite6/urls.py", line 19, in <module>
    from app01.views import AdminView, LoginView
  File "/var/www/html/mysite6/./app01/views.py", line 5, in <module>
    from rest_framework.viewsets import ModelViewSet
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 27, in <module>
    from rest_framework import generics, mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/__init__.py", line 33, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_simplejwt.authentication.JWTAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'rest_framework_simplejwt'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 177, in import_from_string
    return import_string(val)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework_simplejwt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 184, in handle_uncaught_exception
    callback = resolver.resolve_error_handler(500)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 704, in resolve_error_handler
    callback = getattr(self.urlconf_module, "handler%s" % view_type, None)
  File "/usr/local/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.9/site-packages/django/urls/resolvers.py", line 683, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/mysite6/./mysite6/urls.py", line 19, in <module>
    from app01.views import AdminView, LoginView
  File "/var/www/html/mysite6/./app01/views.py", line 5, in <module>
    from rest_framework.viewsets import ModelViewSet
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 27, in <module>
    from rest_framework import generics, mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 17, in <module>
    from rest_framework.schemas import DefaultSchema
  File "/usr/local/lib/python3.9/site-packages/rest_framework/schemas/__init__.py", line 33, in <module>
    authentication_classes=api_settings.DEFAULT_AUTHENTICATION_CLASSES,
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in perform_import
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 168, in <listcomp>
    return [import_from_string(item, setting_name) for item in val]
  File "/usr/local/lib/python3.9/site-packages/rest_framework/settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'rest_framework_simplejwt.authentication.JWTAuthentication' for API setting 'DEFAULT_AUTHENTICATION_CLASSES'. ModuleNotFoundError: No module named 'rest_framework_simplejwt'.
{address space usage: 159121408 bytes/151MB} {rss usage: 37683200 bytes/35MB} [pid: 20|app: 0|req: 1/1] 172.23.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:42:17 2023] POST /api/login/ => generated 0 bytes in 672 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[uwsgi-python-reloader] module/file /var/www/html/mysite6/./mysite6/settings.py has been modified
...gracefully killing workers...
Gracefully killing worker 1 (pid: 20)...
[uwsgi-python-reloader] module/file /var/www/html/mysite6/./mysite6/settings.py has been modified
Gracefully killing worker 2 (pid: 22)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/html/mysite6
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/html/mysite6/uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:44:11 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:28:10
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: e24c7034d9af
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:8000 fd 3
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x560a5bcd3fd0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x560a5bcd3fd0 pid: 19 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 19)
spawned uWSGI worker 1 (pid: 24, cores: 1)
spawned uWSGI worker 2 (pid: 26, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:44:36 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:28:10
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: e24c7034d9af
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5592d085c410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5592d085c410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
{address space usage: 161411072 bytes/153MB} {rss usage: 40054784 bytes/38MB} [pid: 24|app: 0|req: 1/1] 172.23.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:44:58 2023] POST /api/login/ => generated 143 bytes in 149 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)
{address space usage: 161411072 bytes/153MB} {rss usage: 40054784 bytes/38MB} [pid: 24|app: 0|req: 2/2] 172.23.0.1 () {50 vars in 786 bytes} [Sat Apr 22 03:45:14 2023] GET / => generated 143 bytes in 11 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)
{address space usage: 161411072 bytes/153MB} {rss usage: 40054784 bytes/38MB} [pid: 24|app: 0|req: 3/3] 172.23.0.1 () {50 vars in 786 bytes} [Sat Apr 22 03:45:17 2023] GET / => generated 143 bytes in 10 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)
[uwsgi-python-reloader] module/file /var/www/html/mysite6/./mysite6/settings.py has been modified
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24)...
Gracefully killing worker 1 (pid: 22)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /var/www/html/mysite6
closing all non-uwsgi socket fds > 2 (max_fd = 1048576)...
found fd 3 mapped to socket 0 (0.0.0.0:8000)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from /var/www/html/mysite6/uwsgi.ini
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:46:32 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:28:10
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: e24c7034d9af
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 0.0.0.0:8000 fd 3
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55e3806cafd0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55e3806cafd0 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 26, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 28, cores: 1)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:46:56 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:28:10
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: e24c7034d9af
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55d5e1563410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55d5e1563410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
{address space usage: 159047680 bytes/151MB} {rss usage: 39190528 bytes/37MB} [pid: 22|app: 0|req: 1/1] 172.23.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:47:02 2023] POST /api/login/ => generated 52 bytes in 312 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 03:53:53 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 03:49:14
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 482faf28a568
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55b0db72c410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55b0db72c410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
{address space usage: 159047680 bytes/151MB} {rss usage: 39571456 bytes/37MB} [pid: 24|app: 0|req: 1/1] 172.25.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:53:57 2023] POST /api/login/ => generated 52 bytes in 251 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
/usr/local/lib/python3.9/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'app01.models.Admin'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
{address space usage: 159309824 bytes/151MB} {rss usage: 39858176 bytes/38MB} [pid: 24|app: 0|req: 2/2] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:55:40 2023] GET /api/admin/?page=1 => generated 517 bytes in 40 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159309824 bytes/151MB} {rss usage: 39858176 bytes/38MB} [pid: 24|app: 0|req: 3/3] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:55:42 2023] GET /api/admin/?page=2 => generated 160 bytes in 34 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 39858176 bytes/38MB} [pid: 24|app: 0|req: 4/4] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:55:43 2023] GET /api/admin/?page=1 => generated 517 bytes in 33 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 5/5] 172.25.0.1 () {48 vars in 755 bytes} [Sat Apr 22 03:55:49 2023] GET /api/admin/?page=1 => generated 58 bytes in 3 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
{address space usage: 159043584 bytes/151MB} {rss usage: 39563264 bytes/37MB} [pid: 22|app: 0|req: 1/6] 172.25.0.1 () {54 vars in 853 bytes} [Sat Apr 22 03:55:57 2023] POST /api/login/ => generated 52 bytes in 258 msecs (HTTP/1.1 200) 9 headers in 282 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 6/7] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:55:57 2023] GET /api/admin/?page=1 => generated 517 bytes in 35 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 7/8] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:55:59 2023] GET /api/admin/?page=2 => generated 160 bytes in 39 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 8/9] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:56:00 2023] GET /api/admin/?page=1 => generated 517 bytes in 40 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 9/10] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:57:32 2023] GET /api/admin/?page=2 => generated 160 bytes in 37 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 10/11] 172.25.0.1 () {50 vars in 823 bytes} [Sat Apr 22 03:57:33 2023] GET /api/admin/?page=1 => generated 517 bytes in 31 msecs (HTTP/1.1 200) 8 headers in 254 bytes (1 switches on core 0)
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 11/12] 172.25.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:57:47 2023] POST /api/login/ => generated 52 bytes in 121 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 12/13] 172.25.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:58:03 2023] POST /api/login/ => generated 68 bytes in 120 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 159571968 bytes/152MB} {rss usage: 40091648 bytes/38MB} [pid: 24|app: 0|req: 13/14] 172.25.0.1 () {42 vars in 710 bytes} [Sat Apr 22 03:58:49 2023] POST /api/login/ => generated 68 bytes in 121 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 06:51:17 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:44:21
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 435c812c444c
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x558dd0cf0410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/html/mysite6/./mysite6/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 141, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 369, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 231, in contribute_to_class
    self.db_table, connection.ops.max_name_length()
  File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
    return getattr(self._connections[self._alias], item)
  File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
    conn = self.create_connection(alias)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 193, in create_connection
    backend = load_backend(db["ENGINE"])
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 113, in load_backend
    return import_module("%s.base" % backend_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18)
spawned uWSGI worker 1 (pid: 19, cores: 1)
spawned uWSGI worker 2 (pid: 21, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 06:56:30 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: a7a57995353e
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55b3869de410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55b3869de410 pid: 20 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20)
spawned uWSGI worker 1 (pid: 21, cores: 1)
spawned uWSGI worker 2 (pid: 23, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 07:17:53 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: b60f0a589c5c
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5612d6c3d410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5612d6c3d410 pid: 20 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20)
spawned uWSGI worker 1 (pid: 21, cores: 1)
spawned uWSGI worker 2 (pid: 23, cores: 1)
Python auto-reloader enabled
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 07:58:21 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 0242f2a01357
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x565438f42410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x565438f42410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
Bad Request: /api/login/
{address space usage: 158064640 bytes/150MB} {rss usage: 39444480 bytes/37MB} [pid: 24|app: 0|req: 1/1] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 07:59:13 2023] POST /api/login/ => generated 68 bytes in 219 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
{address space usage: 158326784 bytes/150MB} {rss usage: 39845888 bytes/38MB} [pid: 24|app: 0|req: 2/2] 172.30.0.1 () {42 vars in 716 bytes} [Sat Apr 22 07:59:26 2023] POST /api/register/ => generated 34 bytes in 15 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158064640 bytes/150MB} {rss usage: 38420480 bytes/36MB} [pid: 22|app: 0|req: 1/3] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 07:59:35 2023] POST /api/login/ => generated 68 bytes in 112 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158064640 bytes/150MB} {rss usage: 38420480 bytes/36MB} [pid: 22|app: 0|req: 2/4] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 07:59:45 2023] POST /api/login/ => generated 68 bytes in 4 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
{address space usage: 158326784 bytes/150MB} {rss usage: 39845888 bytes/38MB} [pid: 24|app: 0|req: 3/5] 172.30.0.1 () {42 vars in 716 bytes} [Sat Apr 22 08:08:35 2023] POST /api/register/ => generated 35 bytes in 14 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158064640 bytes/150MB} {rss usage: 38420480 bytes/36MB} [pid: 22|app: 0|req: 3/6] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 08:08:58 2023] POST /api/login/ => generated 68 bytes in 4 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158466048 bytes/151MB} {rss usage: 39845888 bytes/38MB} [pid: 24|app: 0|req: 4/7] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 08:10:16 2023] POST /api/login/ => generated 68 bytes in 4 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158466048 bytes/151MB} {rss usage: 39845888 bytes/38MB} [pid: 24|app: 0|req: 5/8] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 08:10:27 2023] POST /api/login/ => generated 68 bytes in 6 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 08:56:58 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 0242f2a01357
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55ec57259410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55ec57259410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
{address space usage: 158060544 bytes/150MB} {rss usage: 38535168 bytes/36MB} [pid: 24|app: 0|req: 1/1] 172.30.0.1 () {42 vars in 716 bytes} [Sat Apr 22 08:57:27 2023] POST /api/register/ => generated 58 bytes in 99 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 2/2] 172.30.0.1 () {42 vars in 716 bytes} [Sat Apr 22 08:57:53 2023] POST /api/register/ => generated 33 bytes in 112 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
{address space usage: 158068736 bytes/150MB} {rss usage: 39395328 bytes/37MB} [pid: 22|app: 0|req: 1/3] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 08:58:04 2023] POST /api/login/ => generated 52 bytes in 186 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 3/4] 172.30.0.1 () {40 vars in 644 bytes} [Sat Apr 22 09:00:28 2023] GET /api/admin/?page=1 => generated 58 bytes in 2 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 4/5] 172.30.0.1 () {40 vars in 644 bytes} [Sat Apr 22 09:00:28 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 5/6] 172.30.0.1 () {40 vars in 653 bytes} [Sat Apr 22 09:00:28 2023] GET /api/admin/?page=1 => generated 58 bytes in 2 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 6/7] 172.30.0.1 () {40 vars in 634 bytes} [Sat Apr 22 09:00:28 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 7/8] 172.30.0.1 () {48 vars in 755 bytes} [Sat Apr 22 09:00:28 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 8/9] 172.30.0.1 () {40 vars in 644 bytes} [Sat Apr 22 09:00:29 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158060544 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 9/10] 172.30.0.1 () {40 vars in 644 bytes} [Sat Apr 22 09:00:29 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158322688 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 10/11] 172.30.0.1 () {40 vars in 653 bytes} [Sat Apr 22 09:00:29 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158322688 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 11/12] 172.30.0.1 () {40 vars in 634 bytes} [Sat Apr 22 09:00:29 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Unauthorized: /api/admin/
{address space usage: 158322688 bytes/150MB} {rss usage: 39886848 bytes/38MB} [pid: 24|app: 0|req: 12/13] 172.30.0.1 () {48 vars in 755 bytes} [Sat Apr 22 09:00:29 2023] GET /api/admin/?page=1 => generated 58 bytes in 1 msecs (HTTP/1.1 401) 9 headers in 288 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158068736 bytes/150MB} {rss usage: 39514112 bytes/37MB} [pid: 22|app: 0|req: 2/14] 172.30.0.1 () {54 vars in 853 bytes} [Sat Apr 22 09:00:59 2023] POST /api/login/ => generated 68 bytes in 5 msecs (HTTP/1.1 400) 9 headers in 291 bytes (1 switches on core 0)
{address space usage: 158461952 bytes/151MB} {rss usage: 40103936 bytes/38MB} [pid: 24|app: 0|req: 13/15] 172.30.0.1 () {54 vars in 853 bytes} [Sat Apr 22 09:01:15 2023] POST /api/login/ => generated 52 bytes in 112 msecs (HTTP/1.1 200) 9 headers in 282 bytes (1 switches on core 0)
/usr/local/lib/python3.9/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'app01.models.Admin'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
{address space usage: 158461952 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 14/16] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 09:01:16 2023] GET /api/admin/?page=1 => generated 52 bytes in 9 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
{address space usage: 158461952 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 15/17] 172.30.0.1 () {56 vars in 927 bytes} [Sat Apr 22 09:01:31 2023] POST /api/admin/ => generated 38 bytes in 10 msecs (HTTP/1.1 201) 9 headers in 298 bytes (1 switches on core 0)
/usr/local/lib/python3.9/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'app01.models.Admin'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
{address space usage: 158330880 bytes/150MB} {rss usage: 39907328 bytes/38MB} [pid: 22|app: 0|req: 3/18] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 09:01:31 2023] GET /api/admin/?page=1 => generated 90 bytes in 7 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
{address space usage: 158461952 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 16/19] 172.30.0.1 () {56 vars in 930 bytes} [Sat Apr 22 09:01:41 2023] PUT /api/admin/1/ => generated 40 bytes in 13 msecs (HTTP/1.1 200) 9 headers in 307 bytes (1 switches on core 0)
{address space usage: 158461952 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 17/20] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 09:01:41 2023] GET /api/admin/?page=1 => generated 92 bytes in 4 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
{address space usage: 158724096 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 18/21] 172.30.0.1 () {54 vars in 878 bytes} [Sat Apr 22 09:01:45 2023] DELETE /api/admin/1/ => generated 0 bytes in 9 msecs (HTTP/1.1 204) 8 headers in 282 bytes (1 switches on core 0)
{address space usage: 158724096 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 19/22] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 09:01:45 2023] GET /api/admin/?page=1 => generated 52 bytes in 4 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
{address space usage: 158724096 bytes/151MB} {rss usage: 40206336 bytes/38MB} [pid: 24|app: 0|req: 20/23] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 09:01:50 2023] GET /api/admin/?page=1 => generated 52 bytes in 5 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 10:26:52 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 0242f2a01357
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
setgid() to 33
setuid() to 33
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33133 (port auto-assigned) fd 3
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x5605941f4960
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5605941f4960 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
spawned uWSGI http 1 (pid: 26)
Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Bad Request: /boundary=--------------------------369126174644689179830013 CONTENT_LENGTH 276 REQUEST_URI api/login/	 PATH_INFO /api/login/ DOCUMENT_ROOT /etc/nginx/html SERVER_PROTOCOL HTTP/1.1 REQUEST_SCHEME http REMOTE_ADDR
 172.30.0.1 REMOTE_PORT 56004 SERVER_PORT 80 SERVER_NAME	 localhost HTTP_USER_AGENT PostmanRuntime/7.31.1 HTTP_ACCEPT */* HTTP_POSTMAN_TOKEN$ eb1b9a78-748d-4bb4-9b62-db8a8ac82a1f	 HTTP_HOST 127.0.0.1:80 HTTP_ACCEPT_ENCODING gzip,
{address space usage: 158674944 bytes/151MB} {rss usage: 38342656 bytes/36MB} [pid: 24|app: 0|req: 1/1] 172.30.0.4 () {24 vars in 1492 bytes} [Sat Apr 22 10:28:19 2023]  boundary=--------------------------369126174644689179830013 => generated 65756 bytes in 139 msecs (deflate, br 400) 4 headers in 383 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Bad Request: /boundary=--------------------------954344831355701653715011 CONTENT_LENGTH 278 REQUEST_URI api/register/	 PATH_INFO /api/register/ DOCUMENT_ROOT /etc/nginx/html SERVER_PROTOCOL HTTP/1.1 REQUEST_SCHEME http REMOTE_ADDR
 172.30.0.1 REMOTE_PORT 56004 SERVER_PORT 80 SERVER_NAME	 localhost HTTP_USER_AGENT PostmanRuntime/7.31.1 HTTP_ACCEPT */* HTTP_POSTMAN_TOKEN$ fefda756-06a3-4d04-9185-6e388f24151e	 HTTP_HOST 127.0.0.1:80 HTTP_ACCEPT_ENCODING gzip,
{address space usage: 158674944 bytes/151MB} {rss usage: 38604800 bytes/36MB} [pid: 24|app: 0|req: 2/2] 172.30.0.4 () {24 vars in 1504 bytes} [Sat Apr 22 10:28:48 2023]  boundary=--------------------------954344831355701653715011 => generated 65772 bytes in 25 msecs (deflate, br 400) 4 headers in 383 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.9/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.9/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0242f2a01357:8000'. You may need to add '0242f2a01357' to ALLOWED_HOSTS.
Bad Request: /boundary=--------------------------506381315473770121797099 CONTENT_LENGTH 278 REQUEST_URI api/register/	 PATH_INFO /api/register/ DOCUMENT_ROOT /etc/nginx/html SERVER_PROTOCOL HTTP/1.1 REQUEST_SCHEME http REMOTE_ADDR
 172.30.0.1 REMOTE_PORT 56004 SERVER_PORT 80 SERVER_NAME	 localhost HTTP_USER_AGENT PostmanRuntime/7.31.1 HTTP_ACCEPT */* HTTP_POSTMAN_TOKEN$ 683104ce-1709-4dbb-bc54-2b536edb2e98	 HTTP_HOST 127.0.0.1:80 HTTP_ACCEPT_ENCODING gzip,
{address space usage: 158674944 bytes/151MB} {rss usage: 38604800 bytes/36MB} [pid: 24|app: 0|req: 3/3] 172.30.0.4 () {24 vars in 1504 bytes} [Sat Apr 22 10:29:02 2023]  boundary=--------------------------506381315473770121797099 => generated 65772 bytes in 22 msecs (deflate, br 400) 4 headers in 383 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 10:35:48 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 06:53:58
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 0242f2a01357
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55ebd6e52410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55ebd6e52410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
{address space usage: 158146560 bytes/150MB} {rss usage: 39804928 bytes/37MB} [pid: 24|app: 0|req: 1/1] 172.30.0.1 () {42 vars in 716 bytes} [Sat Apr 22 10:36:06 2023] POST /api/register/ => generated 34 bytes in 230 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
{address space usage: 158408704 bytes/151MB} {rss usage: 40034304 bytes/38MB} [pid: 24|app: 0|req: 2/2] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 10:37:08 2023] POST /api/login/ => generated 52 bytes in 123 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
{address space usage: 158408704 bytes/151MB} {rss usage: 40034304 bytes/38MB} [pid: 24|app: 0|req: 3/3] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 10:39:18 2023] POST /api/login/ => generated 52 bytes in 120 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158142464 bytes/150MB} {rss usage: 39587840 bytes/37MB} [pid: 22|app: 0|req: 1/4] 172.30.0.1 () {54 vars in 852 bytes} [Sat Apr 22 10:49:31 2023] POST /api/login/ => generated 68 bytes in 274 msecs (HTTP/1.1 400) 9 headers in 291 bytes (1 switches on core 0)
{address space usage: 158142464 bytes/150MB} {rss usage: 39587840 bytes/37MB} [pid: 22|app: 0|req: 2/5] 172.30.0.1 () {54 vars in 852 bytes} [Sat Apr 22 10:49:34 2023] POST /api/login/ => generated 52 bytes in 114 msecs (HTTP/1.1 200) 9 headers in 282 bytes (1 switches on core 0)
/usr/local/lib/python3.9/site-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'app01.models.Admin'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
{address space usage: 158408704 bytes/151MB} {rss usage: 40251392 bytes/38MB} [pid: 24|app: 0|req: 4/6] 172.30.0.1 () {50 vars in 823 bytes} [Sat Apr 22 10:49:36 2023] GET /api/admin/?page=1 => generated 52 bytes in 8 msecs (HTTP/1.1 200) 8 headers in 253 bytes (1 switches on core 0)
{address space usage: 158142464 bytes/150MB} {rss usage: 39587840 bytes/37MB} [pid: 22|app: 0|req: 3/7] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 10:56:18 2023] POST /api/login/ => generated 52 bytes in 114 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
{address space usage: 158142464 bytes/150MB} {rss usage: 39587840 bytes/37MB} [pid: 22|app: 0|req: 4/8] 172.30.0.1 () {42 vars in 710 bytes} [Sat Apr 22 10:56:34 2023] POST /api/login/ => generated 52 bytes in 116 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 13:38:01 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 13:36:27
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 424d22abd4f0
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x56362fd8b410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56362fd8b410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
Bad Request: /api/login/
{address space usage: 158064640 bytes/150MB} {rss usage: 39510016 bytes/37MB} [pid: 22|app: 0|req: 1/1] 192.168.96.1 () {42 vars in 712 bytes} [Sat Apr 22 13:38:26 2023] POST /api/login/ => generated 68 bytes in 221 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
{address space usage: 158056448 bytes/150MB} {rss usage: 39809024 bytes/37MB} [pid: 24|app: 0|req: 1/2] 192.168.96.1 () {42 vars in 718 bytes} [Sat Apr 22 13:38:44 2023] POST /api/register/ => generated 34 bytes in 260 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
{address space usage: 158453760 bytes/151MB} {rss usage: 39923712 bytes/38MB} [pid: 24|app: 0|req: 2/3] 192.168.96.1 () {42 vars in 712 bytes} [Sat Apr 22 13:38:52 2023] POST /api/login/ => generated 52 bytes in 102 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Sat Apr 22 13:45:22 2023] ***
compiled with version: 10.2.1 20210110 on 22 April 2023 13:36:27
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 6329ca02e32f
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x55b25a690410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b25a690410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24, cores: 1)
Bad Request: /api/login/
{address space usage: 158146560 bytes/150MB} {rss usage: 39407616 bytes/37MB} [pid: 24|app: 0|req: 1/1] 192.168.112.1 () {42 vars in 713 bytes} [Sat Apr 22 13:45:38 2023] POST /api/login/ => generated 68 bytes in 224 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
{address space usage: 158146560 bytes/150MB} {rss usage: 39698432 bytes/37MB} [pid: 22|app: 0|req: 1/2] 192.168.112.1 () {42 vars in 719 bytes} [Sat Apr 22 13:46:10 2023] POST /api/register/ => generated 34 bytes in 243 msecs (HTTP/1.1 200) 8 headers in 250 bytes (1 switches on core 0)
{address space usage: 158408704 bytes/151MB} {rss usage: 39907328 bytes/38MB} [pid: 22|app: 0|req: 2/3] 192.168.112.1 () {42 vars in 713 bytes} [Sat Apr 22 13:46:18 2023] POST /api/login/ => generated 52 bytes in 107 msecs (HTTP/1.1 200) 8 headers in 242 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Mon Apr 24 09:04:29 2023] ***
compiled with version: 10.2.1 20210110 on 24 April 2023 08:12:39
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 898258bc3e7d
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x561073f6d410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x561073f6d410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
Bad Request: /api/login/
{address space usage: 158146560 bytes/150MB} {rss usage: 39624704 bytes/37MB} [pid: 22|app: 0|req: 1/1] 172.19.0.1 () {44 vars in 767 bytes} [Mon Apr 24 09:05:02 2023] POST /api/login/ => generated 68 bytes in 341 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Mon Apr 24 09:09:05 2023] ***
compiled with version: 10.2.1 20210110 on 24 April 2023 08:12:39
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 501eff373070
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x560518b68410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x560518b68410 pid: 22 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22)
spawned uWSGI worker 1 (pid: 23, cores: 1)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 25, cores: 1)
Bad Request: /api/login/
{address space usage: 158150656 bytes/150MB} {rss usage: 39661568 bytes/37MB} [pid: 25|app: 0|req: 1/1] 172.20.0.1 () {44 vars in 767 bytes} [Mon Apr 24 09:10:02 2023] POST /api/login/ => generated 68 bytes in 395 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158150656 bytes/150MB} {rss usage: 39682048 bytes/37MB} [pid: 25|app: 0|req: 2/2] 172.20.0.1 () {44 vars in 767 bytes} [Mon Apr 24 09:10:06 2023] POST /api/login/ => generated 68 bytes in 116 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
Method Not Allowed: /
{address space usage: 157327360 bytes/150MB} {rss usage: 36872192 bytes/35MB} [pid: 23|app: 0|req: 1/3] 172.20.0.1 () {44 vars in 747 bytes} [Mon Apr 24 09:10:24 2023] POST / => generated 41 bytes in 185 msecs (HTTP/1.1 405) 8 headers in 271 bytes (1 switches on core 0)
{address space usage: 158150656 bytes/150MB} {rss usage: 39845888 bytes/38MB} [pid: 25|app: 0|req: 3/4] 172.20.0.1 () {44 vars in 746 bytes} [Mon Apr 24 09:10:31 2023] GET / => generated 46 bytes in 4 msecs (HTTP/1.1 200) 8 headers in 255 bytes (1 switches on core 0)
Method Not Allowed: /api/login/
{address space usage: 158150656 bytes/150MB} {rss usage: 39845888 bytes/38MB} [pid: 25|app: 0|req: 4/5] 172.20.0.1 () {44 vars in 766 bytes} [Mon Apr 24 09:12:02 2023] GET /api/login/ => generated 40 bytes in 1 msecs (HTTP/1.1 405) 8 headers in 258 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 158150656 bytes/150MB} {rss usage: 39845888 bytes/38MB} [pid: 25|app: 0|req: 5/6] 172.20.0.1 () {44 vars in 767 bytes} [Mon Apr 24 09:12:07 2023] POST /api/login/ => generated 68 bytes in 126 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Mon Apr 24 09:23:25 2023] ***
compiled with version: 10.2.1 20210110 on 24 April 2023 08:12:39
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: 900b2dd82292
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x560a71e85410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x560a71e85410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
Method Not Allowed: /api/login/
{address space usage: 157323264 bytes/150MB} {rss usage: 37060608 bytes/35MB} [pid: 24|app: 0|req: 1/1] 172.21.0.1 () {40 vars in 556 bytes} [Mon Apr 24 09:23:51 2023] GET /api/login/ => generated 40 bytes in 125 msecs (HTTP/1.1 405) 8 headers in 258 bytes (1 switches on core 0)
Bad Request: /api/login/
{address space usage: 157585408 bytes/150MB} {rss usage: 37060608 bytes/35MB} [pid: 24|app: 0|req: 2/2] 172.21.0.1 () {42 vars in 582 bytes} [Mon Apr 24 09:23:56 2023] POST /api/login/ => generated 79 bytes in 2 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
{address space usage: 158445568 bytes/151MB} {rss usage: 38273024 bytes/36MB} [pid: 24|app: 0|req: 3/3] 172.21.0.1 () {52 vars in 846 bytes} [Mon Apr 24 09:24:42 2023] GET / => generated 5267 bytes in 38 msecs (HTTP/1.1 200) 9 headers in 401 bytes (1 switches on core 0)
Not Found: /favicon.ico
{address space usage: 157577216 bytes/150MB} {rss usage: 37359616 bytes/35MB} [pid: 22|app: 0|req: 1/4] 172.21.0.1 () {50 vars in 787 bytes} [Mon Apr 24 09:24:42 2023] GET /favicon.ico => generated 3156 bytes in 146 msecs (HTTP/1.1 404) 7 headers in 229 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.21 (64bit) on [Mon Apr 24 10:38:23 2023] ***
compiled with version: 10.2.1 20210110 on 24 April 2023 08:12:39
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: dc2791fe3878
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /var/www/html/mysite6
writing pidfile to /tmp/mysite6-master.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /var/www/html/mysite6
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8000 fd 3
setgid() to 33
setuid() to 33
Python version: 3.9.16 (main, Apr 12 2023, 14:54:44)  [GCC 10.2.1 20210110]
Python main interpreter initialized at 0x556704dc6410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 403077 bytes (393 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x556704dc6410 pid: 21 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21)
spawned uWSGI worker 1 (pid: 22, cores: 1)
spawned uWSGI worker 2 (pid: 24, cores: 1)
Python auto-reloader enabled
Bad Request: /api/login/
{address space usage: 157323264 bytes/150MB} {rss usage: 37023744 bytes/35MB} [pid: 24|app: 0|req: 1/1] 172.22.0.1 () {42 vars in 582 bytes} [Mon Apr 24 10:39:19 2023] POST /api/login/ => generated 79 bytes in 129 msecs (HTTP/1.1 400) 8 headers in 251 bytes (1 switches on core 0)
